export const CREATE_USER = "CREATE_USER"

export const CREATE_COLLECTION = "CREATE_COLLECTION"
export const GET_COLLECTION = "GET_COLLECTION"
export const DELETE_COLLECTION = "DELETE_COLLECTION"

export const CREATE_NOTE = "CREATE_NOTE"
export const GET_NOTE = "GET_NOTE"
export const UPDATE_NOTE = "UPDATE_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"